name: flutter_navigation_app
description: flutter_navigation_app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http:
  json_annotation: 3.1.1
  build_runner:

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: 3.5.1

flutter:
  uses-material-design: true
  fonts:
   - family: PermanentMarker
     fonts:
      - asset: fonts/PermanentMarker-Regular.ttf


